### ISSUE TITLE
Test https://monolith.fishandwhistle.net/argo as Argo mirror

### ISSUE THREAD

**Issue by cgrdn** [ArgoCanada/bgcArgoDMQC#46]
Test that Dewey's mirror will work (once config for `default_url` is built, see #44), and then test speed against ifremer and godae GDACS.

**Comment by cgrdn** [comment]
Ok I misunderstood and I think it will be more work than is worth it, especially if the package will eventually switch to argopy for file handling.

**Comment by richardsc** [comment]
Is that because argopy is not built to handle other Argo mirrors? I don't know the details but IIRC it is a pretty easy thing to include depending on how you've coded the urls (ifremer and usgodae) are probably already supported, right?

I was reminded of why more mirrors is a good thing in argoFloats today because I could not get the ifremer https OR FTP to work for downloading files for awhile (this seems to happen from time to time).

**Comment by cgrdn** [comment]
No no, I have a feeling argopy would handle it just fine. I haven't implemented argopy into bgcArgoDMQC yet, but was just thinking I might try plugging Dewey's mirror into my own clunky FTP code. So I'm saying not worth it for me to come up with original code to work with mirrors other than ifremer and usgodae when I'm going to eventually use a separate package for data fetching.
